#ifndef DATA_H
#define DATA_H

#include <stdbool.h>

/**
 * Tuples as they are generated by the data generator (left input; stream R).
 *
 * The schema [ x:int, y:float, z:char[20] ] is adapted from the
 * CellJoin paper.
 */
typedef int   x_t;
typedef float y_t;
typedef char  z_t[20];

/**
 * Tuples as they are generated by the data generator (right input).
 *
 * The schema [ a:int, b:float, c:double, d:bool ] is adapted from the
 * CellJoin paper.
 */
typedef int    a_t;
typedef float  b_t;
typedef double c_t;
typedef bool   d_t;

struct master_ctx_t;
void generate_data(struct master_ctx_t *ctx);

#endif  /* DATA_H */
