# Postprocesses a folder generated by zmq_bench
# for each measure in the folder the follwing actions are performed:
#	1. removes last lines of measurements which may include missing values
#	2. computes the average power consumption and saves it in result.csv
#	3. generates energy plot for each measurement

if [ -z $1 ]; 
then 
	echo "usage: ./postprocess [measurement folder]"; 
else
	./tools/lastline_rem.sh $1
	python ./tools/csv_avg.py $1/
	#python3 ./tools/gen_energy_plots.py $1
	mv result.csv $1
fi
